### ISSUE TITLE
Compatible with El Capitan?

### ISSUE THREAD

**Issue by MaplesThroughWindows** [breiter/blueutil#1]
Hi,

I'm considering upgrading from Mavericks.  Does this utility still work on El Capitan?

Thanks.

**Comment by breiter** [comment]
Yes. Works like a champ on Yosemite and El Capitan.

**Comment by MaplesThroughWindows** [comment]
Hi,

That’s great news.  One less thing to worry about when I migrate to El Capitan.

Kind regards.
